<a href="https://colab.research.google.com/github/Mritunjaysri01/machine_leaning/blob/master/numpy_indexing_and_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

Broad Casting

In [0]:
arr[0:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [0]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_of_Array = arr[0:5]

In [18]:
slice_of_Array

array([0, 1, 2, 3, 4])

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_of_Array[:]=99

In [21]:
slice_of_Array

array([99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [0]:
arr_copy=arr.copy()

In [0]:
arr_copy[:]=100

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [0]:
arr_2d =np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d.shape

(3, 3)

In [31]:
arr_2d[0]

array([ 5, 10, 15])

In [33]:
arr_2d[1]

array([20, 25, 30])

In [35]:
arr_2d[1,1]

25

In [37]:
arr_2d[2][1]

40

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [0]:
arr = np.arange(1,11)

In [42]:
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
bool_arr  = arr>4

In [45]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
arr = np.arange(0,10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])