<a href="https://colab.research.google.com/github/Mritunjaysri01/machine_leaning/blob/master/numpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print("hello")

hello


In [0]:
import seaborn as sns

In [0]:
import tensorflow as tf


In [0]:
tf.__version__

'2.2.0'

In [0]:
import numpy as np

In [0]:
mylist = [1,2,3]

In [0]:
np.array(mylist)

array([1, 2, 3])

In [0]:
nested_list = [[1,2],[3,4],[5,6]]

In [0]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [0]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
np.ones(3)

array([1., 1., 1.])

In [0]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [0]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [0]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
np.random.rand(2)

array([0.05631915, 0.1559786 ])

In [0]:
np.random.rand(3,4)

array([[0.2356015 , 0.90666808, 0.38330081, 0.71445007],
       [0.99637395, 0.22198443, 0.52034917, 0.80790753],
       [0.01920602, 0.26083815, 0.08870669, 0.12209995]])

In [0]:
np.random.randn(5,5)

array([[-1.07787479,  0.2492391 , -0.17725123, -0.45552084, -0.35781969],
       [-1.04210633,  0.22081309,  0.535401  ,  0.26536289,  0.12275345],
       [-0.48407194, -0.54567329,  0.69798176, -0.36946492,  0.02261634],
       [ 0.14397401, -2.4713725 , -1.14905916,  0.11585498,  2.60921851],
       [-0.4146758 ,  0.14831728, -0.04633371,  0.21183339,  1.08793707]])

In [0]:
np.random.randint(1,100,(2,99))

array([[76, 32, 80, 63, 42, 52, 18, 26, 54, 46, 31, 10, 37, 28, 44, 31,
        46, 75, 12, 40, 90, 13,  4, 31, 43, 68,  8, 31, 66,  6, 47, 19,
        41, 30, 22, 58, 14, 83, 24, 99, 51, 42, 78, 85,  5,  4,  3, 40,
        78, 55, 36, 44, 52, 63, 18, 97, 45, 46, 54, 24,  3, 40, 76, 59,
        19, 10,  2, 71, 26, 27,  3, 19, 41, 37, 85, 64, 75, 59, 72, 15,
        31, 50, 78, 76, 94, 12, 52, 68, 65, 64, 82, 41,  1,  1, 89, 57,
        80, 70, 92],
       [81, 45,  9, 30, 45, 13, 29, 55, 88, 34, 21, 59, 77, 86, 89, 53,
        78, 21, 74, 22, 91, 15, 76, 11, 71, 15, 83, 70, 35, 96, 14, 80,
        31, 97, 95, 57, 54, 10, 86, 88, 37, 19, 58, 61, 12, 37, 38, 72,
        75, 50, 39, 92, 13, 10, 48, 69, 71, 58, 67, 76, 88, 46, 28, 76,
        82, 98, 95, 83, 31,  6, 78, 57, 49, 95, 20, 43, 75, 70, 95, 51,
        15, 33, 96, 65, 52,  8, 91, 93, 32, 55, 65, 56, 74, 21, 46, 48,
         5, 90, 26]])

In [0]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [0]:
arr = np.arange(25)

In [0]:
  ranarr = np.random.randint(0,50,10)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [0]:
arr.shape 

(25,)

In [0]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
  arr.reshape(3,6)

ValueError: ignored

In [0]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [0]:
ranarr.max()

39

In [0]:
ranarr.min()

2

In [0]:
ranarr.argmax()

7

In [0]:
ranarr.argmin()

9

In [0]:
ranarr.dtype

dtype('int64')

In [0]:
myarr=np.random.rand(4)

In [0]:
myarr

array([0.18182497, 0.18340451, 0.30424224, 0.52475643])

In [0]:
myarr.dtype

dtype('float64')